// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type blog = Collections['blog']['schema']['_output']
export declare const blog: blog[]
